### PR TITLE
Catch webhook db errors

### LINKED ISSUE #1257: Webhook deliveries fail when build was requested by new site
If a build was requested by the new snapcraft.io site, then (of course) no `BuildRequestAnnotation` row is created in build.snapcraft.io.  However, a webhook delivery is still made to build.snapcraft.io if the snap was created before the new site existed.  This delivery attempt returns HTTP 500 because it fails to create a `BuildAnnotation` row since it has no `BuildRequestAnnotation` to link it to.

Speaking as the author of the code that creates a `BuildAnnotation`, it was a mistake that it returns 500 in this case.  If you compare `src/server/handlers/launchpad.js:internalRequestSnapBuilds` with `src/server/handlers/webhook.js:handleLaunchpadSnapBuild`, you'll see that both claim to do best-effort creation of database rows, but only the former has an exception handler that makes it be actually best-effort.

The consequence of the HTTP 500s is that webhook delivery attempts get backed up in Launchpad; so it would be very helpful to fix this as part of the transition to the new site.

### PR DESCRIPTION
**Pull request by jkfran**
## Done

Fixes #1257

### CODE REVIEW

File: src/server/handlers/webhook.js [hunk 1]
```diff
@@ -104,14 +104,21 @@ const handleLaunchpadSnapBuild = async (req, res, owner, name, parsedBody) => {
...
+              .forge({
+                build_id: getLinkId(parsedBody.snap_build),
+                request_id: getLinkId(parsedBody.build_request)
+              })
+              .save({}, { method: 'insert', transacting: trx });
+          });
+        } catch (error) {
+          logger.error(
+            'Error saving build request annotation for ' +
+            `${parsedBody.build_request}: ${error}`
```
Comment (cjwatson) [inline src/server/handlers/webhook.js:119]: The error is in saving a build annotation, not a build request annotation, so this error message isn't quite right.  By the same token, it probably ought to refer to `parsedBody.snap_build` rather than `parsedBody.build_request`.

Comment (jkfran) [reply src/server/handlers/webhook.js]: It makes sense. Let me know if it's okay now.
